services:
  mysql8033:
    container_name: mysql8033_vini
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    restart: always
    environment:
      MYSQL_DATABASE: site_vini_dev
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/dbs:/var/lib/mysql
